#6 breakdown pt4 - add generated files and subgraph
cowdao-grants/cow-py pull request #13
Opened 2024-08-15 21:51 UTC by yvesfracari

original PR: cowdao-grants#6

Add generated files and subgraph module

2024-08-29 13:51 UTC, ribeirojose approved these changes

2024-08-29 16:43 UTC, mendesfabio approved these changes

2024-09-04 19:17 UTC, ribeirojose commented
`#must` implement e2e tests for the Orderbook API https://github.com/cowdao-grants/cow-py/pull/9#discussion_r1744251295

2024-09-04 19:17 UTC, ribeirojose requested changes
`#must` implement e2e tests for the Orderbook API https://github.com/cowdao-grants/cow-py/pull/9#discussion_r1744251295

2024-09-10 14:39 UTC, ribeirojose commented
> `#must` implement e2e tests for the Orderbook API [#9 (comment)](https://github.com/cowdao-grants/cow-py/pull/9#discussion_r1744251295)

done in #12

2024-09-10 14:40 UTC, ribeirojose approved these changes

2024-09-10 14:41 UTC, ribeirojose commented
CoW's hosted service subgraph is down so will add another issue to come back to fixing it and unblock the other parts of this PR

2024-09-10 14:45 UTC, merged